base_url = "https://www.fwvain.faith"
title = "vain"
build_search_index = false
generate_feed = true
compile_sass = true
minify_html = true

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle" # light, dark, auto, toggle
# mathjax = true
# mathjax_dollar_inline_enable = true

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
]

socials = [
    { name = "twitter", url = "https://twitter.com/fwvain", icon = "twitter" },
    { name = "github", url = "https://github.com/h3samayoa/", icon = "github" },
]

custom_css = []
