name: Build and Publish to AWS
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        
      - name: install zola
        uses: taiki-e/install-action@v2.18.15
        with:
          tool: zola@0.17.2
          
      - name: Build
        run: zola build

      - name: list dir 
        run: ls -R 
      
      - name: Deploy site to S3
        run: |
          aws s3 sync ./public s3://${{ secrets.S3_BUCKET }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-1
